version: '3'

networks:
  proxynet:
    external:
      name: "{{ docker.network }}"
  default:
    driver: bridge

services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      # TODO: fix mailer settings
      - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME="https://wallabag.{{ vault_domain.name }}"
      - SYMFONY__ENV__SERVER_NAME="Conflux Wallabag instance"
    networks:
      - default
      - "{{ docker.network }}"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=wallabag"
      - "traefik.frontend.rule=Host:wallabag.{{ vault_domain.name }}"
    volumes:
      - "{{ docker.data_dir }}/wallabag/images:/var/www/wallabag/web/assets/images"
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost/api/info"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis

  db:
    image: mariadb:11
    container_name: wallabag-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - "{{ docker.data_dir }}/wallabag/db:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s

  redis:
    image: redis:alpine
    container_name: wallabag-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
