version: "3.3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8888:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      FTLCONF_LOCAL_IPV4: ${MYIP}
    volumes:
      - "${DATADIR}/pihole/etc-pihole:/etc/pihole"
      - "${DATADIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
