---
# All non-secret vars that can be stored safely in public Git repository 

zfs: { 
  pool_name: 'tank',
  disk1: '/dev/disk/by-id/ata-ST4000VN008-2DR166_ZDHB0FZK',
  disk2: '/dev/disk/by-id/ata-ST4000VN008-2DR166_ZDH1P0F2',
} 