networks:
  proxynet:
    external:
      name: "{{ docker.network }}"
  default:
    driver: bridge

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST={{ vault_domain.name }}
      - WG_DEFAULT_DNS={{ net.gateway }}
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0, {{ net.net }}
      - PASSWORD_HASH={{ vault.wireguard.password_hash }}
    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker.data_dir }}/wireguard/config:/etc/wireguard"
    networks:
      - default
      - "{{ docker.network }}"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.port=51821"
      - "traefik.backend=wireguard"
      - "traefik.frontend.rule=Host:wireguard.{{ vault_domain.name }}"