---
  - name: "Setting up the homeserver"
    connection: local
    hosts: localhost

    # Become root user, which is needed for most tasks
    become: yes
    become_user: root

    vars_files:
        - vars/main.yaml
        - vars/vault.yaml

    roles:
      - role: samba
        tags: samba

    tasks:
    - import_tasks: tasks/zfs.yaml
    - import_tasks: tasks/users.yaml
