---
- name: Create folder for traefik data
  file:
    path: "{{docker.data_dir}}/traefik/acme"
    state: directory

- name: Create acme config file for traefik
  file:
    path: "{{docker.data_dir}}/traefik/acme/acme.json"
    state: touch
    mode: '0600'

- name: Copy treafik config file
  template:
    src: traefik.toml
    dest: "{{docker.data_dir}}/traefik/traefik.toml"

- name: Create the external docker network {{docker.network}}
  docker_network:
    name: "{{docker.network}}"

- name: Create and start traefik service
  community.docker.docker_compose:
    project_name: traefik
    definition:
      version: "3.3"
      networks:
        proxynet:
          external:
            name: "{{ docker.network }}"
        default:
          driver: bridge
      services:
        traefik:
          hostname: traefik
          image: traefik:v1.7.16
          container_name: traefik
          restart: unless-stopped
          domainname: "{{ vault_domain.name }}"
          networks:
            - default
            - "{{ docker.network }}"
          ports:
            - "80:80"
            - "443:443"
            - "7080:8080"
          environment:
            TZ: "{{docker.tz}}"
            OVH_ENDPOINT: ovh-eu
            OVH_APPLICATION_KEY: "{{vault_ovh.application_key}}"
            OVH_APPLICATION_SECRET: "{{vault_ovh.application_secret}}"
            OVH_CONSUMER_KEY: "{{vault_ovh.consumer_key}}"
          labels:
            - "traefik.enable=true"
            - "traefik.backend=traefik"
            - "traefik.frontend.rule=Host:traefik.{{ vault_domain.name }}"
            - "traefik.port=8080"
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "{{ docker.data_dir }}/traefik/traefik.toml:/traefik.toml"
            - "{{ docker.data_dir }}/traefik/acme:/etc/traefik/acme"
